spring:
  application:
    name: "master-dataset"
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

parquet:
  max-records: 1000 # rotacja pliku po n rekordach