spring:
  application:
    name: master-dataset
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

hdfs:
  uri: hdfs://namenode:8020

parquet:
  max-records: 1000 # rotacja pliku po n rekordach
  compression-codec: GZIP
